# Generated by Django 4.1.6 on 2023-03-24 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairhireapp", "0002_chatroom_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="complaint_token",
            field=models.CharField(
                default=12345678,
                max_length=8,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="requester",
            field=models.CharField(max_length=255),
        ),
    ]
