# Generated by Django 4.0.3 on 2023-03-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairhireapp', '0003_complaints_complaint_token_alter_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
